"""create core tables

Revision ID: 2c05821ed624
Revises: 
Create Date: 2026-07-27 10:15:01.873799
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '2c05821ed624'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('crawl_policy', sa.JSON(), nullable=False),
    sa.Column('rate_limit_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_source_type'), 'data_sources', ['source_type'], unique=False)
    op.create_table('evaluation_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_text', sa.Text(), nullable=False),
    sa.Column('sample_category', sa.String(length=50), nullable=False),
    sa.Column('risk_labels', sa.JSON(), nullable=False),
    sa.Column('expected_evidence', sa.JSON(), nullable=False),
    sa.Column('construction_basis', sa.Text(), nullable=False),
    sa.Column('authenticity_type', sa.String(length=50), nullable=False),
    sa.Column('split', sa.String(length=50), nullable=False),
    sa.Column('final_review_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('export_path', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('field_reviews_json', sa.JSON(), nullable=False),
    sa.Column('corrections_json', sa.JSON(), nullable=False),
    sa.Column('evidence_quality', sa.String(length=1), nullable=False),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('reviewer', sa.String(length=255), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['review_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=4096), nullable=True),
    sa.Column('final_url', sa.String(length=4096), nullable=True),
    sa.Column('source_title', sa.String(length=1000), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('raw_file_path', sa.String(length=2048), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('authenticity_type', sa.String(length=50), nullable=False),
    sa.Column('collection_status', sa.String(length=50), nullable=False),
    sa.Column('parse_status', sa.String(length=50), nullable=False),
    sa.Column('final_review_status', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('corrected_fields_json', sa.JSON(), nullable=False),
    sa.Column('knowledge_index_status', sa.String(length=50), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_data_type'), 'source_documents', ['data_type'], unique=False)
    op.create_index(op.f('ix_source_documents_final_review_status'), 'source_documents', ['final_review_status'], unique=False)
    op.create_index(op.f('ix_source_documents_sha256'), 'source_documents', ['sha256'], unique=True)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.String(length=1000), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('punished_entity', sa.String(length=500), nullable=True),
    sa.Column('authority', sa.String(length=255), nullable=True),
    sa.Column('document_number', sa.String(length=255), nullable=True),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('illegal_facts', sa.Text(), nullable=False),
    sa.Column('legal_basis', sa.Text(), nullable=True),
    sa.Column('penalty_result', sa.Text(), nullable=True),
    sa.Column('original_sales_wording_disclosed', sa.Boolean(), nullable=False),
    sa.Column('original_sales_wording', sa.Text(), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=False),
    sa.Column('final_review_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_penalties_document_id'), 'penalties', ['document_id'], unique=False)
    op.create_table('product_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=500), nullable=True),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('product_type', sa.String(length=255), nullable=True),
    sa.Column('waiting_period', sa.Text(), nullable=True),
    sa.Column('cooling_off_period', sa.Text(), nullable=True),
    sa.Column('insurance_responsibility', sa.Text(), nullable=True),
    sa.Column('exclusions', sa.Text(), nullable=True),
    sa.Column('cash_value_description', sa.Text(), nullable=True),
    sa.Column('guaranteed_benefit', sa.Text(), nullable=True),
    sa.Column('non_guaranteed_benefit', sa.Text(), nullable=True),
    sa.Column('surrender_risk', sa.Text(), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=False),
    sa.Column('final_review_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_documents_document_id'), 'product_documents', ['document_id'], unique=False)
    op.create_table('regulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('document_number', sa.String(length=255), nullable=True),
    sa.Column('issuing_authority', sa.String(length=255), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('validity_status', sa.String(length=50), nullable=True),
    sa.Column('article_number', sa.String(length=100), nullable=True),
    sa.Column('article_text', sa.Text(), nullable=False),
    sa.Column('source_quote', sa.Text(), nullable=False),
    sa.Column('final_review_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulations_document_id'), 'regulations', ['document_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regulations_document_id'), table_name='regulations')
    op.drop_table('regulations')
    op.drop_index(op.f('ix_product_documents_document_id'), table_name='product_documents')
    op.drop_table('product_documents')
    op.drop_index(op.f('ix_penalties_document_id'), table_name='penalties')
    op.drop_table('penalties')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_source_documents_sha256'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_final_review_status'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_data_type'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_table('review_decisions')
    op.drop_table('status_history')
    op.drop_table('review_batches')
    op.drop_table('evaluation_samples')
    op.drop_index(op.f('ix_data_sources_source_type'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
